package com.roomreservation.reservation.repository;

import org.springframework.data.jpa.repository.JpaRepository;

import com.roomreservation.reservation.domain.Reservation;

/**
 * Reservation 엔티티에 대한 JPA Repository 인터페이스
 * - 기본적인 CRUD 기능 제공 (생성, 조회, 수정, 삭제)
 * - JpaRepository를 상속하여 구현체 없이 자동 생성됨
 * 
 * JPA Repository interface for Reservation entity
 * - Provides basic CRUD operations (Create, Read, Update, Delete)
 * - Implementation is auto-generated by extending JpaRepository
 */
public interface ReservationRepository extends JpaRepository<Reservation, Long> {
    
}