package com.roomreservation.reservation.repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;

import com.roomreservation.reservation.domain.User;

/**
 * User 엔티티에 대한 JPA Repository 인터페이스
 * - 기본적인 CRUD 기능 제공 (저장, 조회, 수정, 삭제)
 * - JpaRepository를 상속하여 구현체 없이 자동 생성됨
 * 
 * JPA Repository interface for User entity
 * - Provides basic CRUD operations (Create, Read, Update, Delete)
 * - Implementation is auto-generated by extending JpaRepository
 */
public interface UserRepository extends JpaRepository<User, Long> {
    Optional<User> findByEmail(String email);
}